### ISSUE TITLE
error in getting jsonp

### ISSUE THREAD

**Issue by praveenprasad** [aFarkas/Ajaxmanager#10]
this pluggin throws error when tried to get jsonp with cacheResult=true

eg:
            var options = {
                url: 'http://gdata.youtube.com/feeds/api/videos',
                type: 'get',
                cache: false,
                data: {
                    q: 'india',
                    alt: 'json-in-script',
                    'max-results': 10,
                    format: 5,
                    'start-index': 1,
                    orderby: 'published'
                },
                dataType: 'jsonp',
                success: function (data) {
                    if (console) {
                       console.log('data received');
                    }
                }
            };

var someManagedAjax = $.manageAjax.create('someAjaxProfileName', { queue: true, cacheResponse: false,cacheTTL:7000 });
someManagedAjax.add(options);

cacheResponse=true: will throw error
cacheResponse= false: would not

**Comment by aFarkas** [comment]
thanks for the bug report
