### ISSUE TITLE
incompatible jquery 1.5.1 ?

### ISSUE THREAD

**Issue by itechnology** [aFarkas/Ajaxmanager#12]
Can't say for sure since i'm on vacation right now, but the other day when i implemented ajaxmanager 3.0 with jquery 1.5.1 nothing worked, i got some error about "label something" (they did rewrite the whole ajax pipeline tho), when i switched back to jquery 1.4.4 everything worked again.

Sorry for the vague information...

Robert

**Comment by aFarkas** [comment]
It is incompatible with jQuery 1.5. I will make a new release.

**Comment by chobo2** [comment]
@aFarkas  - I just came to ask the same question if Ajax manager works with the new Ajax way in 1.5. Do you know when the new release will be out?

**Comment by aFarkas** [comment]
I hope, I can have a beta out this week. I will fix incompatibility issues and add a deferred object as a return value instead of an id.

**Comment by aFarkas** [comment]
Hi,

I have testet ajaxmanager and it seems fine to use with jQuery 1.5.1. Please try version 3.11 from the repository. currently it returns the id and not a deffered object. I hope, I can add this feature soon.

cheers
alex

**Comment by itechnology** [comment]
Still on vacation, but will test this Monday morning when i get back to work!

Thank's 
Robert

**Comment by itechnology** [comment]
Ok just finished testing/debugging ..the problem is still there but seems like it's a bug that was introduced with 1.5.1.

On many ajax queries i get an error with: invalid label

Found this page:
http://bugs.jquery.com/ticket/8452

which lead me here:
http://bugs.jquery.com/ticket/8084

so i added 
        jsonp: null,
        jsonpCallback: null,

to my ajax requests, and now it works with ajaxmanager.

So i guess for now it's either use 1.4.4 or use this workaround with 1.5.1 with the risk of breaking jsonp.

## 

Robert
