### ISSUE TITLE
JQuery 1.5 DataType Bug

### ISSUE THREAD

**Issue by clarkni5** [aFarkas/Ajaxmanager#13]
I am using JQuery 1.5.1 with the latest copy of Ajaxmanager, version 3.11 (the commit comments say "simple jquery 1.5.1 compatibility").

When making request with the option { dataType: "json" }, I get an error. In Firefox, the error says "Invalid label" and in Chrome, it says, "Uncaught SyntaxError: Unexpected token :".

It looks like this error is related to extending/overriding $.ajaxSettings. If I change this line of code:
this.opts = $.extend({}, $.ajaxSettings, $.manageAjax.defaults, opts);
To this:
this.opts = $.extend({}, $.manageAjax.defaults, opts);
Then the error goes away.

It looks like the new way of implementing this type of functionality is to use prefilters. The JQuery validation plugin was throwing similar errors and they released a fix using the new prefilter callbacks. Here are the related docs.
http://api.jquery.com/extending-ajax/

I don't understand the problem well enough to submit a patch, so I hope this is enough information to identify the problem and I'm hoping there is an easy fix for future releases.

A temporary fix is to use the option { dataType: "text json" }. This seems to correct for the problem.

**Comment by aFarkas** [comment]
@clarkni
Thanks, I haven't testet this yet. But I'm sure, that your change will be the fix:
this.opts = $.extend({}, $.manageAjax.defaults, opts);

The use of $.ajaxSettings isn't needed anymore and can be removed without any problems.

**Comment by aFarkas** [comment]
@clarkni:

I have now pushed the fix. My change was to remove $.ajaxSettings + add async: true as a new default of $.manageAjax.defaults.

Can you look, wether this fixes your issue, without causing a new one?

regards
alex

**Comment by clarkni5** [comment]
Looks good. I use this in several scripts and they are all working properly.

Thanks Alex!

-Nick
