### ISSUE TITLE
(NS_ERROR_NOT_AVAILABLE) [nsIXMLHttpRequest.status]" nsresult: "0x80040111

### ISSUE THREAD

**Issue by BStramke** [aFarkas/Ajaxmanager#2]
Playing around with the script i found an error occuring sometimes:

uncaught exception: [Exception... "Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIXMLHttpRequest.status]" nsresult: "0x80040111 (NS_ERROR_NOT_AVAILABLE)" location: "JS frame :: http://192.168.161.100/js/jquery/jquery.ajaxmanager.js :: anonymous :: line 80" data: no]

which refers to this line: 
var httpStatus  = ahr.status,

According to this page it is not allowed to direclty read the .status value:
http://helpful.knobs-dials.com/index.php/%22Component_returned_failure_code:_0x80040111_%28NS_ERROR_NOT_AVAILABLE%29%22

(needs try/catch block as it seems, but i don't really know for sure).

PS: Adding the try{}catch(err){} block will then throw the timeout error which should be correct.

**Comment by aFarkas** [comment]
Thx, for your bugreport. Can you confirm this bug in the newest version (3.0.2)?

**Comment by BStramke** [comment]
I tested it and the timeout error was thrown, so it should be fixed. Thank you for your Bugfix Release :-)
