### ISSUE TITLE
When using cached results XHR object is not available for querying

### ISSUE THREAD

**Issue by novoj** [aFarkas/Ajaxmanager#4]
Though it seems logical is some situations it complicates business logic counting on data in XHR object. For example if someone checks xhr.status in success callback, or examines response headers. I've prepared patch where object imitating is cached along with the data - callbacks can then examine the XHR the same as original XHR in no cached situation.

**Comment by novoj** [comment]
Hmm, there is no option to upload file :-(

# Index: jquery.ajaxmanager.js

RCS file: /www/CVS/p_java/cps/libs_java/lib_form/lib_form_core/src/main/resources/META-INF/lib_form/globalResources/jQuery/jquery.ajaxmanager.js,v
retrieving revision 1.2
diff -u -r1.2 jquery.ajaxmanager.js
--- jquery.ajaxmanager.js   6 May 2010 14:04:25 -0000   1.2
+++ jquery.ajaxmanager.js   15 Sep 2010 13:13:10 -0000
@@ -114,8 +114,8 @@
                if(o.cacheResponse && cache[id]){
                    that.requests[id] = {};
                    setTimeout(function(){
-                       that._complete.call(that, o.context || o, origCom, {}, 'success', id, o);
-                       that._success.call(that, o.context || o, origSuc, cache[id], 'success', {}, o);
-                       that._complete.call(that, o.context || o, origCom, cache[id], 'success', id, o);
-                       that._success.call(that, o.context || o, origSuc, cache[id].responseText, 'success', cache[id], o);
                  }, 0);
              } else {
                  that.requests[id] = $.ajax(o);
  @@ -175,8 +175,24 @@
                  that.abort(name);
              });
          }
-           if(o.cacheResponse && !cache[o.xhrID]){
-               cache[o.xhrID] = data;
-           if(o.cacheResponse && !cache[o.xhrID]){  
-                var parsedHeaders = {};
-                var headers = xhr.getAllResponseHeaders();
-                var headerItems = headers.split("\n");
-                for (var key in headerItems) {
-                    var headerItem = headerItems[key];
-                    var delimiter = headerItem.indexOf(":");
-                    var headerName = headerItem.substr(0, delimiter);
-                    parsedHeaders[headerName] = headerItem.substr(delimiter + 2);
-                }
-                cache[o.xhrID] = {
-                    status: xhr.status,
-                    statusText: xhr.statusText,
-                    responseText: xhr.responseText,
-                    responseXML: xhr.responseXML,
-                    getAllResponseHeaders: function() {return xhr.getAllResponseHeaders();},
-                    getResponseHeader: function(name) {return parsedHeaders[name];}
-                };
          }
          origFn.call(context, data, status, xhr, o);
          $.event.trigger(this.name +'AjaxSuccess', [xhr, o, data]);

**Comment by aFarkas** [comment]
Hi Jan,

this was intended, but I took your suggestions and commited your changes. I made some tweaks here and there. Note, that I won't return responseText, but the succesData, due to the fact, that jQuery sometimes is processing the answer (json). Please have a look @http://github.com/aFarkas/Ajaxmanager/commit/ddbf0e350b437f6866c90726599dc6ccbdfdc73b and be so kind to review the code/changes, before I release the code.

regards
alex

**Comment by novoj** [comment]
Hello Alex,

   I've tested current Github version with my code and it works well - also all the tweaks you have done seem pretty good. Thank you for adopting the patch.

Regards,
Jan
