### ISSUE TITLE
IE6 null or not an object error

### ISSUE THREAD

**Issue by xpepermint** [aFarkas/Ajaxmanager#6]
In IE6 I have "null or not an object error" when cacheResponse=true.
Go to your site http://www.protofunc.com/scripts/jquery/ajaxManager/ and click the laste example.

Note: getAllResponseHeaders was introduced in Windows Internet Explorer 7.

I guess it would be enough to just disable functions for old browsers.

**Comment by aFarkas** [comment]
Thanks, I will fix this.

**Comment by aFarkas** [comment]
I made the [changes](https://github.com/aFarkas/Ajaxmanager/commit/a39ecb4cbdbaa0103e88ae6515866b306536efa6) and already made a quick release. Can you look into this, confirm, that the bug isn't there anymore?

Thanks again.

**Comment by xpepermint** [comment]
Yup, good job man!
