### ISSUE TITLE
When using JSONP, callbacks don't seem to be fired

### ISSUE THREAD

**Issue by sylvinus** [aFarkas/Ajaxmanager#7]

**Comment by aFarkas** [comment]
I can confirm this bug. Ajaxmanager currently only handles XHRs well.

**Comment by aFarkas** [comment]
I have pushed a fix for this. I have to make some additional browser tests, to mark this fix as final, but if you need to get this fixed as soon, you can try the newest version

**Comment by aFarkas** [comment]
Hi,

would you like to test manager RC3.0.9 to confirm, that erverything is working, as expected?

regards
Alex
