### ISSUE TITLE
JSLint Conformance

### ISSUE THREAD

**Issue by krohrsb** [aFarkas/Ajaxmanager#8]
Hi! Could you possibly update the source to be JSLint Compliant?
http://jslint.com/
Formatting it correctly beforehand helps a bit:
http://jsbeautifier.org/

Unless you disagree with both these tools, though I'd be curious as to why if you did :)
Thanks!
-Kyle

**Comment by krohrsb** [comment]
Ah, I forgot. When JSLinting please use 'The Good Parts' button when picking the options.

**Comment by aFarkas** [comment]
I have released the version + added a "use strict";. I partially disagree, but let me some time to explain why.

**Comment by krohrsb** [comment]
Ah I did not mean to use 'strict' mode, I would avoid it in this case even. I just meant JSLinting with 'The Good Parts' options, as well as formatting it properly. I look forward to your thoughts! I may take my fork and update it as I am thinking as well.
